---
## for older systems, use fmem
## FIXME! rpm packages from https://forensics.cert.org/
- name: FATAL
  fail: msg="Missing memory size! required for fmem."
  when: memory_size is undefined

- name: Debian | Extra packages install
  apt:
    name: ['make', 'gcc', 'linux-generic', 'linux-headers-{{ ansible_kernel }}']
    state: present
  become: yes
  when: memcapture_install is defined and memcapture_install
  register: pkg_result
  until: pkg_result is success

- name: Check if fmem archive is present
  stat:
    path: "{{ bin_path }}/fmem_{{ memcapture_fmem_v }}.tgz"
  register: fmem
- name: fmem download
  get_url:
    url: "http://hysteria.cz/niekt0/fmem/fmem_{{ memcapture_fmem_v }}.tgz"
    dest: "{{ bin_path }}/fmem_{{ memcapture_fmem_v }}.tgz"
    mode: '0400'
  when: not fmem.stat.exists and (memcapture_download is defined and memcapture_download)
- name: Extract fmem
  unarchive:
    src: "{{ bin_path }}/fmem_{{ memcapture_fmem_v }}.tgz"
    dest: "{{ bin_path }}"
  when: not fmem.stat.exists and (memcapture_download is defined and memcapture_download)

# change memory size

- name: Check if already a capture file
  stat: path={{ dst_path }}/{{ prefix }}-fmem-memory.img
  register: memcapture2
- name: FMEM | procinfo
  shell: "{{ item }}"
  with_items:
    - "cat /proc/meminfo > {{ dst_path }}/{{ prefix }}-proc-meminfo"
    - "cat /proc/iomem > {{ dst_path }}/{{ prefix }}-proc-iomem"
    - "cat /proc/mtrr > {{ dst_path }}/{{ prefix }}-proc-mtrr"
  when: not memcapture2.stat.exists

- name: Check if fmem.ko exists
  stat: path={{ bin_path }}/fmem_{{ memcapture_fmem_v }}/fmem.ko
  register: fmemko
## fmem.ko is probably kernel dependent, so better rebuild... or prebuilt
- name: FMEM | memory capture
  command: "{{ item }} chdir={{ bin_path }}/fmem_{{ memcapture_fmem_v }}"
  with_items:
    - make
  when: not fmemko.stat.exists and (memcapture_build is defined and memcapture_build)

## if multiple pre-compiled fmem
#- copy: src={{ bin_path }}/fmem_{{ memcapture_fmem_v }}/run.sh dest={{ dst_path }}/run.sh mode=0755
#- replace:
#    dest: "{{ dst_path }}/run.sh"
#    regexp: 'fmem.ko'
#    replace: '{{ bin_path }}/fmem_{{ memcapture_fmem_v }}/fmem-{{ ansible_kernel }}.ko'

- name: FMEM | memory capture (1)
  command: "./run.sh chdir={{ bin_path }}/fmem_{{ memcapture_fmem_v }}"
  become: yes
## if run.sh/fmem.ko already loaded
  ignore_errors: true
  when: not memcapture2.stat.exists and (memcapture_capture is defined and memcapture_capture)
- name: FMEM | memory capture (2)
  command: >
    dd if=/dev/fmem of={{ dst_path }}/{{ prefix }}-memory-fmem.img conv=noerror,sync bs={{ memcapture_memory_bs }}
        count={{ memcapture_memory_size }}
  args:
    chdir: "{{ bin_path }}/fmem_{{ memcapture_fmem_v }}"
  become: yes
  when: not memcapture2.stat.exists and (memcapture_capture is defined and memcapture_capture)

- name: retrieve output hash
  stat: path="{{ dst_path }}/{{ prefix }}-memory-fmem.img" checksum_algorithm=sha256
  register: outputstat
- debug: var=outputstat.stat.checksum
