---

- set_fact:
    osxpmem_archive: "{{ bin_path }}/{{ memcapture_osxpmem_url | regex_replace('^.*/([^/].*)$', '\\1') }}"
- set_fact:
    osxpmem_bin: "{{ osxpmem_archive | regex_replace('.zip$', '') }}"
    osxpmem_capture: "{{ dst_path }}/{{ prefix }}-memory.{{ memcapture_linpmem_ext }}"

- stat: path={{ osxpmem_archive }}
  register: osxpmem
- name: Osxpmem download
  get_url: url="{{ memcapture_osxpmem_url }}"
    dest="{{ osxpmem_archive }}"
    mode=0400
  when: not osxpmem.stat.exists and (do_download is defined and do_download)

- stat: path={{ osxpmem_bin }}
  register: bin
- command: extract osxpmem
  unarchive: "src={{ dst_path }}/{{ osxpmem_archive }} dest={{ osxpmem_bin }} mode=0700"
  when: not bin.stat.exists

- stat: path={{ osxpmem_capture }}
  register: memcapture2
- name: do memory capture (osxpmem)
  command: "{{ osxpmem_bin }} -o {{ osxpmem_capture }}"
  when: not memcapture2.stat.exists and (memcapture_capture is defined and memcapture_capture)

