---

- name: Set fact avml_bin
  ansible.builtin.set_fact:
    avml_bin: "{{ memcapture_bin_path }}/avml-minimal"
    avml_capture: "{{ dst_path }}/{{ prefix }}-memory-avml.{{ memcapture_avml_ext }}"

- name: Microsoft avml-minimal download
  ansible.builtin.get_url:
    url: "{{ memcapture_avml_bin }}"
    dest: "{{ avml_bin }}"
    mode: '0700'
  register: dl_result
  until: dl_result is success
  when: memcapture_download|bool

- name: Install avml locally
  ansible.builtin.copy:
    src: "{{ avml_bin }}"
    dest: /usr/local/bin/
    mode: '0700'
    remote_src: true
  when: memcapture_install|bool
