---

- set_fact:
    winpmem_bin: "{{ bin_path }}\\{{ memcapture_winpmem_url | regex_replace('^.*/([^/].*)$', '\\1') }}"
    winpmem_capture: "{{ dst_path }}\\{{ prefix }}-memory.{{ memcapture_winpmem_ext }}"

- win_stat: path="{{ winpmem_bin }}"
  register: winpmem
- name: winpmem download
  win_get_url: url="{{ memcapture_winpmem_url }}"
    dest="{{ winpmem_bin }}"
    mode=0400
  when: not winpmem.stat.exists and (do_download is defined and do_download)

- win_stat: path="{{ winpmem_capture }}"
  register: memcapture2

## FIXME! through powershell ? (ansible 'script:')
- name: Do memory capture (winpmem)
  raw: "{{ winpmem_bin }} -o {{ winpmem_capture }}"
  when: not memcapture2.stat.exists and (memcapture_capture is defined and memcapture_capture)

## https://docs.google.com/presentation/d/1savcvqRcMXpRyVrybWvbHGbJTgjInZcwLB5VokJdKa8/edit#slide=id.g26dcd0ccb_030
#"c:\Program Files\Rekall\winpmem_1.6.0.exe" -e - | c:\Users\mic\Desktop\ncat.exe 172.16.21.93 8001  --ssl
#ncat -l 8001 --ssl -v > myimage.elf

## https://technet.microsoft.com/en-us/sysinternals/bb897438.aspx
- name: force sync aka write to disk
  raw: "{{ bin_path }}\\sync.exe -r -e"

