---

- name: Check if existing avml capture
  stat:
    path: "{{ avml_capture }}"
  register: memcapture2

- name: memory capture (avml)
  command: "/usr/local/bin/avml {{ memcapture_avml_args }} {{ avml_capture }}"
  args:
    chdir: "{{ memcapture_bin_path }}"
  become: yes
  when: not memcapture2.stat.exists and (memcapture_capture is defined and memcapture_capture|bool)
  failed_when: false

- name: retrieve output hash
  stat:
    path: "{{ avml_capture }}"
    checksum_algorithm: sha256
  register: outputstat
- name: Debug | file output hash
  debug: var=outputstat.stat.checksum
