---

- name: Microsoft Avml-convert download
  ansible.builtin.get_url:
    url: "{{ memcapture_avmlconvert_bin }}"
    dest: "{{ memcapture_bin_path }}/avml-convert"
    mode: '0700'
  register: dl_result
  until: dl_result is success
  when: (memcapture_download is defined and memcapture_download|bool)

- name: Install avml locally
  ansible.builtin.copy:
    src: "{{ memcapture_bin_path }}/avml-convert"
    dest: /usr/local/bin/
    mode: '0700'
    remote_src: true
  when: memcapture_install|bool
