FROM alpine:3.8
RUN apk update

# Install Ansible
RUN apk add git alpine-sdk libffi-dev openssl-dev py3-crypto py3-jinja2 py3-markupsafe py3-paramiko py3-yaml python3 python3-dev
RUN pip3 install ansible
RUN mkdir /etc/ansible

# Install Ansible inventory file
RUN (echo "[local]"; echo "localhost ansible_connection=local") > /etc/ansible/hosts
