# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/jammy64"
    #config.vm.box = "generic/centos9s"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant', memory_size: 536870912, memcapture_capture: true }
       ansible.groups = {
          "myrole" => ["ubuntu12_32", "ubuntu14_64", "debian76_64", "centos7_64", "centos6_32", "centos5_64", "centos5_32", "centos5_32b", "centos7", "centos6" ],
       }
    end

     config.vm.define "ubuntu12_32" do |ubuntu12_32|
       ubuntu12_32.vm.box = "ubuntu/precise32"
     end
     config.vm.define "ubuntu14_64" do |ubuntu14_64|
       ubuntu14_64.vm.box = "ubuntu/trusty64"
     end
     config.vm.define "debian76_64" do |debian76_64|
       debian76_64.vm.box = "chef/debian-7.6"
     end
     config.vm.define "centos7" do |cfg|
       cfg.vm.box = "centos/7"
     end
     config.vm.define "centos6" do |cfg|
       cfg.vm.box = "centos/6"
     end
     config.vm.define "centos7_64" do |centos7_64|
       centos7_64.vm.box = "puppetlabs/centos-7.0-64-puppet-enterprise"
     end
     config.vm.define "centos6_32" do |centos6_32|
       centos6_32.vm.box = "chef/centos-6.5-i386"
     end
     config.vm.define "centos5_64" do |centos5_64|
       centos5_64.vm.box = "chef/centos-5.10"
     end
     config.vm.define "centos5_32" do |centos5_32|
       centos5_32.vm.box = "chef/centos-5.11-i386"
     end
     config.vm.define "centos5_32b" do |centos5_32b|
       centos5_32b.vm.box = "hansode/centos-5.6-i386"  # minimal
     end

     config.vm.provider "virtualbox" do |v|
       v.memory = 512
     end

end
